sonar.organization=priyanshuchouhan
sonar.projectKey=priyanshuchouhan_family-app
sonar.projectName=family-app

sonar.sources=backend/src
sonar.tests=backend/tests

sonar.exclusions=backend/node_modules/**
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
